# Generated by Django 3.1.2 on 2020-10-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='map.category'),
        ),
        migrations.AddField(
            model_name='marker',
            name='sub_category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='map.subcategory'),
        ),
    ]
